# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='maxs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='minx',
            field=models.IntegerField(default=0),
        ),
    ]
