# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20161206_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Line',
            new_name='lines',
        ),
    ]
