# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20161206_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lines',
            new_name='Newline',
        ),
    ]
